server:
  port: 80

spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    #db1是我众多数据库中，其中一个数据库的名称，db1里面很多表，在这我使用student表
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: root
    #这个是设置druid数据源 ,先要导druid依赖坐标
    type: com.alibaba.druid.pool.DruidDataSource

  #关掉一些无用的打印输出
  main:
    banner-mode: off


#查询日志。可以方便查看具体的SQL语句，没啥实际功能，平时可以关掉，等出了问题再打开log来看原因
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #关闭打印的无用消息
  global-config:
    banner: false





